springdoc:
  api-docs:
      path: '/api/docs'
security:
  expirationDate: 1800000
  userClaim: 'user_id'
  secret: 'NinjaOneRMM'
  authHeader: 'Authorization'
  headerPrefix: 'Bearer'
  loginUrl: '/api/login'
  registerUrl: '/api/register'
apiPrefix: '/api'