root:
  name: 'root'
  email: 'root@ninjaone.rmm'
  password: 'password'

spring:
  output:
    ansi:
      enabled: DETECT
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:ninjaone}?createDatabaseIfNotExist=true'
    username: '${MYSQL_USER:root}'
    password: '${MYSQL_PASS:password}'

springdoc:
  api-docs:
      path: '/api/docs'

security:
  expirationDate: 1800000
  userClaim: 'user_id'
  rolesClaim: 'authorities'
  secret: 'NinjaOneRMM'
  authHeader: 'Authorization'
  headerPrefix: 'Bearer'

api:
  prefix: '/api'
  login: '/api/login'
  register: '/api/register'
  users: '/api/users'
  catalog: '/api/catalog'
  docs: '/api/docs'

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    rmm.ninjaone: DEBUG
    org.hibernate: ERROR
  file:
    name: application.log