spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:ninjaone}?createDatabaseIfNotExist=true'
    username: '${MYSQL_USER:root}'
    password: '${MYSQL_PASS:password}'

springdoc:
  api-docs:
      path: '/api/docs'

security:
  expirationDate: 1800000
  userClaim: 'user_id'
  secret: 'NinjaOneRMM'
  authHeader: 'Authorization'
  headerPrefix: 'Bearer'
  loginUrl: '/api/login'
  registerUrl: '/api/register'

api:
  prefix: '/api'